// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    usuarios,
    proyectos,
    mapas,
    trazados,
    waypoints,
    archivos,
    sincronizaciones,
  ];
  late final Shape0 usuarios = Shape0(
    source: i0.VersionedTable(
      entityName: 'usuarios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 proyectos = Shape1(
    source: i0.VersionedTable(
      entityName: 'proyectos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_6,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mapas = Shape2(
    source: i0.VersionedTable(
      entityName: 'mapas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_17,
        _column_6,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 trazados = Shape3(
    source: i0.VersionedTable(
      entityName: 'trazados',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_17,
        _column_6,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_25,
        _column_14,
        _column_15,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 waypoints = Shape4(
    source: i0.VersionedTable(
      entityName: 'waypoints',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_17,
        _column_42,
        _column_6,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 archivos = Shape5(
    source: i0.VersionedTable(
      entityName: 'archivos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_17,
        _column_42,
        _column_50,
        _column_6,
        _column_31,
        _column_51,
        _column_19,
        _column_21,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sincronizaciones = Shape6(
    source: i0.VersionedTable(
      entityName: 'sincronizaciones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_4,
        _column_0,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_27,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get authUid =>
      columnsByName['auth_uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get correo =>
      columnsByName['correo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rol =>
      columnsByName['rol']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fotoUrl =>
      columnsByName['foto_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sesionVenceEn =>
      columnsByName['sesion_vence_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'codigo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sincronizado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (sincronizado IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'creado_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actualizado_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'auth_uid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nombre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'correo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rol',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'foto_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sesion_vence_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get duenoAuthUid =>
      columnsByName['dueno_auth_uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cliente =>
      columnsByName['cliente']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get municipio =>
      columnsByName['municipio']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get centroLat =>
      columnsByName['centro_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get centroLon =>
      columnsByName['centro_lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get activo =>
      columnsByName['activo']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dueno_auth_uid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cliente',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'municipio',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'centro_lat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'centro_lon',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'activo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (activo IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proyectoCodigo =>
      columnsByName['proyecto_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formatoOrigen =>
      columnsByName['formato_origen']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get llaveS3 =>
      columnsByName['llave_s3']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rutaLocal =>
      columnsByName['ruta_local']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get tamanoMb =>
      columnsByName['tamano_mb']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get srcOrigen =>
      columnsByName['src_origen']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get zoomMin =>
      columnsByName['zoom_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get zoomMax =>
      columnsByName['zoom_max']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get bbox =>
      columnsByName['bbox']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get esquinas =>
      columnsByName['esquinas']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get opacidad =>
      columnsByName['opacidad']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get visible =>
      columnsByName['visible']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'proyecto_codigo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'formato_origen',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'llave_s3',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ruta_local',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tamano_mb',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'src_origen',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'zoom_min',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'zoom_max',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bbox',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'esquinas',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'estado',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'orden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'opacidad',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 1.0',
      defaultValue: const i1.CustomExpression('1.0'),
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'visible',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (visible IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proyectoCodigo =>
      columnsByName['proyecto_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metodo =>
      columnsByName['metodo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get geometria =>
      columnsByName['geometria']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get llaveGeometria =>
      columnsByName['llave_geometria']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bbox =>
      columnsByName['bbox']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get centroLat =>
      columnsByName['centro_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get centroLon =>
      columnsByName['centro_lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get puntos =>
      columnsByName['puntos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get distanciaM =>
      columnsByName['distancia_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get areaHa =>
      columnsByName['area_ha']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get precisionMediaM =>
      columnsByName['precision_media_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get iniciadoEn =>
      columnsByName['iniciado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get terminadoEn =>
      columnsByName['terminado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get usuarioCodigo =>
      columnsByName['usuario_codigo']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metodo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'geometria',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'llave_geometria',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'puntos',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'distancia_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'area_ha',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'precision_media_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'iniciado_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'terminado_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'usuario_codigo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proyectoCodigo =>
      columnsByName['proyecto_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trazadoCodigo =>
      columnsByName['trazado_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitud =>
      columnsByName['latitud']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitud =>
      columnsByName['longitud']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get altitudM =>
      columnsByName['altitud_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get precisionM =>
      columnsByName['precision_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get simbolo =>
      columnsByName['simbolo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nota =>
      columnsByName['nota']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get marcadoEn =>
      columnsByName['marcado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get usuarioCodigo =>
      columnsByName['usuario_codigo']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trazado_codigo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'latitud',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'longitud',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'altitud_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'precision_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'simbolo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nota',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'marcado_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sincronizado =>
      columnsByName['sincronizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizadoEn =>
      columnsByName['actualizado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proyectoCodigo =>
      columnsByName['proyecto_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trazadoCodigo =>
      columnsByName['trazado_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get waypointCodigo =>
      columnsByName['waypoint_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rutaLocal =>
      columnsByName['ruta_local']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get llaveS3 =>
      columnsByName['llave_s3']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get tamanoMb =>
      columnsByName['tamano_mb']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get usuarioCodigo =>
      columnsByName['usuario_codigo']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'waypoint_codigo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ruta_local',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inicio =>
      columnsByName['inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fin =>
      columnsByName['fin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enviados =>
      columnsByName['enviados']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fallidos =>
      columnsByName['fallidos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get detalle =>
      columnsByName['detalle']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inicio',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fin',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enviados',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fallidos',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'detalle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
